import { Share_Tech } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const shareTech = Share_Tech({
  variable: "--font-share-tech",
  subsets: ["latin"],
  weight: "400",
  display: 'swap'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${shareTech.variable} antialiased`}
      >
        <NavBar />
        <div className="p-6">
          {children}
        </div>
      </body>
    </html>
  );
}
